{
  "openapi": "3.0.0",
  "info": {
    "x-katapult-version": "2.68.0",
    "version": "1.0.0",
    "title": "Katapult Core API",
    "description": "Welcome to the documentation for the Katapult Core API"
  },
  "servers": [
    {
      "url": "https://api.katapult.io/core/v1"
    }
  ],
  "paths": {
    "/organizations/organization/api_tokens": {
      "get": {
        "operationId": "get:organization_api_tokens",
        "summary": "List organization API tokens",
        "description": "Returns a list of all API tokens for an organization\n## Scopes\n- `api_tokens`\n- `api_tokens:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "API tokens"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/api_tokens",
              "api.katapult.io/core/v1/api_tokens:read"
            ]
          },
          {
            "Authenticator": [
              "api_tokens",
              "api_tokens:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:organization_api_tokens",
        "summary": "Create API token for organization",
        "description": "Create a new API token for a given organization\n## Scopes\n- `api_tokens`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "API tokens"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/api_tokens"
            ]
          },
          {
            "Authenticator": [
              "api_tokens"
            ]
          }
        ]
      }
    },
    "/api_tokens/api_token": {
      "patch": {
        "operationId": "patch:api_token",
        "summary": "Update organization API token",
        "description": "Updates an organization API token with new properties\n## Scopes\n- `api_tokens`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "API tokens"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/api_tokens"
            ]
          },
          {
            "Authenticator": [
              "api_tokens"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:api_token",
        "summary": "Delete organization API token",
        "description": "Delete an organization API token\n## Scopes\n- `api_tokens`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "API tokens"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/api_tokens"
            ]
          },
          {
            "Authenticator": [
              "api_tokens"
            ]
          }
        ]
      }
    },
    "/api_tokens/api_token/regenerate_secret": {
      "post": {
        "operationId": "post:api_token_regenerate_secret",
        "summary": "Regenerate organization API token secret",
        "description": "Regenerates the secret for an organization API token\n## Scopes\n- `api_tokens`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "API tokens"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/api_tokens"
            ]
          },
          {
            "Authenticator": [
              "api_tokens"
            ]
          }
        ]
      }
    },
    "/organizations/organization/object_storage/object_storage_cluster/access_keys": {
      "post": {
        "operationId": "post:organization_object_storage_object_storage_cluster_access_keys",
        "summary": "Create object storage access key",
        "description": "Create a new access key in an object storage account\n## Scopes\n- `object_storage`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Access keys"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage"
            ]
          },
          {
            "Authenticator": [
              "object_storage"
            ]
          }
        ]
      }
    },
    "/organizations/organization/object_storage/access_keys": {
      "get": {
        "operationId": "get:organization_object_storage_access_keys",
        "summary": "List object storage access keys",
        "description": "Returns a list of all object storage access keys for a given organization\n## Scopes\n- `object_storage`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Access keys"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage"
            ]
          },
          {
            "Authenticator": [
              "object_storage"
            ]
          }
        ]
      }
    },
    "/object_storage/access_keys/access_key/generate_credentials": {
      "post": {
        "operationId": "post:object_storage_access_key_generate_credentials",
        "summary": "Generate object storage S3 access key credentials",
        "description": "Returns new S3 credentials for an object storage access key. Existing credentials cannot be retrieved. Credentials may take a few minutes to become active.\n## Scopes\n- `object_storage`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Access keys"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage"
            ]
          },
          {
            "Authenticator": [
              "object_storage"
            ]
          }
        ]
      }
    },
    "/object_storage/access_keys/access_key": {
      "get": {
        "operationId": "get:object_storage_access_key",
        "summary": "Get object storage access key details",
        "description": "Returns object storage access key details.\n## Scopes\n- `object_storage`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Access keys"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage"
            ]
          },
          {
            "Authenticator": [
              "object_storage"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:object_storage_access_key",
        "summary": "Update object storage access key",
        "description": "Updates an object storage access key with new properties\n## Scopes\n- `object_storage`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Access keys"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage"
            ]
          },
          {
            "Authenticator": [
              "object_storage"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:object_storage_access_key",
        "summary": "Delete object storage access key",
        "description": "Delete an object storage access key\n## Scopes\n- `object_storage`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Access keys"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage"
            ]
          },
          {
            "Authenticator": [
              "object_storage"
            ]
          }
        ]
      }
    },
    "/address_lists/address_list/entries": {
      "get": {
        "operationId": "get:address_list_entries",
        "summary": "List address list entries",
        "description": "Returns a list of all address list entries for a given address list\n## Scopes\n- `address_lists`\n- `address_lists:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Address list entries"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/address_lists",
              "api.katapult.io/core/v1/address_lists:read"
            ]
          },
          {
            "Authenticator": [
              "address_lists",
              "address_lists:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:address_list_entries",
        "summary": "Create address list entry",
        "description": "Create a new address list entry for a given address list.\n## Scopes\n- `address_lists`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Address list entries"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/address_lists"
            ]
          },
          {
            "Authenticator": [
              "address_lists"
            ]
          }
        ]
      }
    },
    "/address_list_entries/address_list_entry": {
      "get": {
        "operationId": "get:address_list_entry",
        "summary": "Get address list entry",
        "description": "Returns details for an address list entry.\n## Scopes\n- `address_lists`\n- `address_lists:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Address list entries"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/address_lists",
              "api.katapult.io/core/v1/address_lists:read"
            ]
          },
          {
            "Authenticator": [
              "address_lists",
              "address_lists:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:address_list_entry",
        "summary": "Update address list entry",
        "description": "Update an address list entry with new properties.\n## Scopes\n- `address_lists`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Address list entries"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/address_lists"
            ]
          },
          {
            "Authenticator": [
              "address_lists"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:address_list_entry",
        "summary": "Delete address list entry",
        "description": "Delete an address list entry.\n## Scopes\n- `address_lists`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Address list entries"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/address_lists"
            ]
          },
          {
            "Authenticator": [
              "address_lists"
            ]
          }
        ]
      }
    },
    "/address_lists/address_list/entries/bulk": {
      "post": {
        "operationId": "post:address_list_entries_bulk",
        "summary": "Bulk change address list entries",
        "description": "Create or delete multiple address list entries for a given address list.\n## Scopes\n- `address_lists`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Address list entries"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/address_lists"
            ]
          },
          {
            "Authenticator": [
              "address_lists"
            ]
          }
        ]
      }
    },
    "/address_lists": {
      "get": {
        "operationId": "get:address_lists",
        "summary": "List global address lists",
        "description": "Returns a list of all global address lists.\n## Scopes\n- `address_lists`\n- `address_lists:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Address lists"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/address_lists",
              "api.katapult.io/core/v1/address_lists:read"
            ]
          },
          {
            "Authenticator": [
              "address_lists",
              "address_lists:read"
            ]
          }
        ]
      }
    },
    "/organizations/organization/address_lists": {
      "get": {
        "operationId": "get:organization_address_lists",
        "summary": "List address lists",
        "description": "Returns a list of all address lists for a given organization\n## Scopes\n- `address_lists`\n- `address_lists:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Address lists"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/address_lists",
              "api.katapult.io/core/v1/address_lists:read"
            ]
          },
          {
            "Authenticator": [
              "address_lists",
              "address_lists:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:organization_address_lists",
        "summary": "Create address list",
        "description": "Create a new address list for a given organization.\n## Scopes\n- `address_lists`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Address lists"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/address_lists"
            ]
          },
          {
            "Authenticator": [
              "address_lists"
            ]
          }
        ]
      }
    },
    "/address_lists/address_list": {
      "get": {
        "operationId": "get:address_list",
        "summary": "Get address list",
        "description": "Returns details for a address list.\n## Scopes\n- `address_lists`\n- `address_lists:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Address lists"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/address_lists",
              "api.katapult.io/core/v1/address_lists:read"
            ]
          },
          {
            "Authenticator": [
              "address_lists",
              "address_lists:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:address_list",
        "summary": "Update address list",
        "description": "Update a address list with new properties.\n## Scopes\n- `address_lists`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Address lists"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/address_lists"
            ]
          },
          {
            "Authenticator": [
              "address_lists"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:address_list",
        "summary": "Delete address list",
        "description": "Delete a address list.\n## Scopes\n- `address_lists`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Address lists"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/address_lists"
            ]
          },
          {
            "Authenticator": [
              "address_lists"
            ]
          }
        ]
      }
    },
    "/organizations/organization/object_storage/object_storage_cluster/buckets": {
      "post": {
        "operationId": "post:organization_object_storage_object_storage_cluster_buckets",
        "summary": "Create object storage bucket",
        "description": "Create a new bucket in an object storage account\n## Scopes\n- `object_storage`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Buckets"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage"
            ]
          },
          {
            "Authenticator": [
              "object_storage"
            ]
          }
        ]
      }
    },
    "/object_storage/object_storage_cluster/buckets/bucket": {
      "patch": {
        "operationId": "patch:object_storage_object_storage_cluster_bucket",
        "summary": "Update object storage bucket",
        "description": "Configure an object storage bucket with new properties\n## Scopes\n- `object_storage`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Buckets"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage"
            ]
          },
          {
            "Authenticator": [
              "object_storage"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:object_storage_object_storage_cluster_bucket",
        "summary": "Delete object storage bucket",
        "description": "Delete an object storage bucket\n## Scopes\n- `object_storage`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Buckets"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage"
            ]
          },
          {
            "Authenticator": [
              "object_storage"
            ]
          }
        ]
      },
      "get": {
        "operationId": "get:object_storage_object_storage_cluster_bucket",
        "summary": "Get an object storage bucket",
        "description": "Returns object storage bucket details\n## Scopes\n- `object_storage:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Buckets"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage:read"
            ]
          },
          {
            "Authenticator": [
              "object_storage:read"
            ]
          }
        ]
      }
    },
    "/object_storage/object_storage_cluster/buckets/bucket/revoke_presigned_urls": {
      "post": {
        "operationId": "post:object_storage_object_storage_cluster_bucket_revoke_presigned_urls",
        "summary": "Revoke object storage bucket presigned URLs",
        "description": "Revoke presigned URLs for all objects within an object storage bucket\n## Scopes\n- `object_storage`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Buckets"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage"
            ]
          },
          {
            "Authenticator": [
              "object_storage"
            ]
          }
        ]
      }
    },
    "/object_storage/object_storage_cluster/buckets/bucket/object": {
      "get": {
        "operationId": "get:object_storage_object_storage_cluster_bucket_object",
        "summary": "Get an object storage object",
        "description": "Returns object storage object details\n## Scopes\n- `object_storage:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Buckets"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage:read"
            ]
          },
          {
            "Authenticator": [
              "object_storage:read"
            ]
          }
        ]
      }
    },
    "/object_storage/object_storage_cluster/buckets/bucket/presigned_url": {
      "post": {
        "operationId": "post:object_storage_object_storage_cluster_bucket_presigned_url",
        "summary": "Create a presigned url for an object storage object",
        "description": "Returns temporary url to download the object storage object\n## Scopes\n- `object_storage`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Buckets"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage"
            ]
          },
          {
            "Authenticator": [
              "object_storage"
            ]
          }
        ]
      }
    },
    "/organizations/organization/virtual_machines/build": {
      "post": {
        "operationId": "post:organization_virtual_machines_build",
        "summary": "Build virtual machine",
        "description": "Builds a new virtual machine based on the arguments provided to this endpoint. Virtual machines will be built in the background. This task will return an task object that will allow you to monitor the build process using the appropriate API action. This action only offers a small subset of the full functionality needed when provisioning virtual machines - see the `build_from_spec` action for a full advanced virtual machine creation method.\n## Scopes\n- `virtual_machines`[...]",
        "tags": [
          "Build"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines"
            ]
          }
        ]
      }
    },
    "/organizations/organization/virtual_machines/build_from_spec": {
      "post": {
        "operationId": "post:organization_virtual_machines_build_from_spec",
        "summary": "Build virtual machine (from spec)",
        "description": "Builds a new virtual machine by receiving a virtual machine spec document\n## Scopes\n- `virtual_machines`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Build"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines"
            ]
          }
        ]
      }
    },
    "/virtual_machines/builds/virtual_machine_build": {
      "get": {
        "operationId": "get:virtual_machines_builds_virtual_machine_build",
        "summary": "Get virtual machine build",
        "description": "Return virtual machine build information\n## Scopes\n- `virtual_machines`\n- `virtual_machines:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Build"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:read"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:read"
            ]
          }
        ]
      }
    },
    "/organizations/organization/certificates": {
      "get": {
        "operationId": "get:organization_certificates",
        "summary": "List certificates",
        "description": "Provides a full list of certificates\n## Scopes\n- `certificates`\n- `certificates:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Certificates"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/certificates",
              "api.katapult.io/core/v1/certificates:read"
            ]
          },
          {
            "Authenticator": [
              "certificates",
              "certificates:read"
            ]
          }
        ]
      }
    },
    "/certificates/certificate": {
      "get": {
        "operationId": "get:certificate",
        "summary": "Get certificate",
        "description": "Return details for a specific certificate\n## Scopes\n- `certificates`\n- `certificates:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Certificates"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/certificates",
              "api.katapult.io/core/v1/certificates:read"
            ]
          },
          {
            "Authenticator": [
              "certificates",
              "certificates:read"
            ]
          }
        ]
      }
    },
    "/virtual_machines/virtual_machine/console_sessions": {
      "post": {
        "operationId": "post:virtual_machine_console_sessions",
        "summary": "Create console session",
        "description": "Creates a new console session which can be opened in a browser\n## Scopes\n- `virtual_machines`\n- `virtual_machines:console`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Console"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:console"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:console"
            ]
          }
        ]
      }
    },
    "/countries": {
      "get": {
        "operationId": "get:countries",
        "summary": "List countries",
        "description": "Return a list of all countries available in Katapult",
        "tags": [
          "Countries"
        ]
      }
    },
    "/countries/country": {
      "get": {
        "operationId": "get:country",
        "summary": "Get country",
        "description": "Return details for a specific country",
        "tags": [
          "Countries"
        ]
      }
    },
    "/countries/country/country_states": {
      "get": {
        "operationId": "get:country_country_states",
        "summary": "List country states",
        "description": "Return a list of all country states for a specific country",
        "tags": [
          "Country states"
        ]
      }
    },
    "/country_states/country_state": {
      "get": {
        "operationId": "get:country_state",
        "summary": "Get country state",
        "description": "Return details for a specific country state",
        "tags": [
          "Country states"
        ]
      }
    },
    "/currencies": {
      "get": {
        "operationId": "get:currencies",
        "summary": "List currencies",
        "description": "Return a list of all currencies available in Katapult",
        "tags": [
          "Currencies"
        ]
      }
    },
    "/currencies/currency": {
      "get": {
        "operationId": "get:currency",
        "summary": "Get currency",
        "description": "Return details for a specific currency",
        "tags": [
          "Currencies"
        ]
      }
    },
    "/organizations/organization/dns_zones": {
      "get": {
        "operationId": "get:organization_dns_zones",
        "summary": "List DNS zones",
        "description": "Return a list of all DNS zones\n## Scopes\n- `dns`\n- `dns:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "DNS zones"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/dns",
              "api.katapult.io/core/v1/dns:read"
            ]
          },
          {
            "Authenticator": [
              "dns",
              "dns:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:organization_dns_zones",
        "summary": "Create DNS zone",
        "description": "Create a new DNS zone within an existing organization\n## Scopes\n- `dns`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "DNS zones"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/dns"
            ]
          },
          {
            "Authenticator": [
              "dns"
            ]
          }
        ]
      }
    },
    "/organizations/organization/dns_zones/nameservers": {
      "get": {
        "operationId": "get:organization_dns_zones_nameservers",
        "summary": "List nameservers",
        "description": "Return a list of nameservers that should be used for DNS zones within a given organization\n## Scopes\n- `dns`\n- `dns:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "DNS zones"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/dns",
              "api.katapult.io/core/v1/dns:read"
            ]
          },
          {
            "Authenticator": [
              "dns",
              "dns:read"
            ]
          }
        ]
      }
    },
    "/dns_zones/dns_zone": {
      "get": {
        "operationId": "get:dns_zone",
        "summary": "Get DNS zone",
        "description": "Return details for a specific DNS zone\n## Scopes\n- `dns`\n- `dns:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "DNS zones"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/dns",
              "api.katapult.io/core/v1/dns:read"
            ]
          },
          {
            "Authenticator": [
              "dns",
              "dns:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:dns_zone",
        "summary": "Update DNS zone",
        "description": "Update properties for a DNS zone\n## Scopes\n- `dns`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "DNS zones"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/dns"
            ]
          },
          {
            "Authenticator": [
              "dns"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:dns_zone",
        "summary": "Delete DNS zone",
        "description": "Delete a DNS zone\n## Scopes\n- `dns`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "DNS zones"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/dns"
            ]
          },
          {
            "Authenticator": [
              "dns"
            ]
          }
        ]
      }
    },
    "/dns_zones/dns_zone/verify": {
      "post": {
        "operationId": "post:dns_zone_verify",
        "summary": "Verify DNS zone",
        "description": "Attempt to verify either the nameservers or root TXT record for a given DNS zone\n## Scopes\n- `dns`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "DNS zones"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/dns"
            ]
          },
          {
            "Authenticator": [
              "dns"
            ]
          }
        ]
      }
    },
    "/data_centers": {
      "get": {
        "operationId": "get:data_centers",
        "summary": "List data centers",
        "description": "Provides a full list of all data centers",
        "tags": [
          "Data centers"
        ]
      }
    },
    "/data_centers/data_center": {
      "get": {
        "operationId": "get:data_center",
        "summary": "Get data center",
        "description": "Provide details for a specific data center",
        "tags": [
          "Data centers"
        ]
      }
    },
    "/data_centers/data_center/default_network": {
      "get": {
        "operationId": "get:data_center_default_network",
        "summary": "Get default network of data center",
        "description": "Provide details of default network for a data center",
        "tags": [
          "Data centers"
        ]
      }
    },
    "/organizations/organization/disk_io_profiles": {
      "get": {
        "operationId": "get:organization_disk_io_profiles",
        "summary": "List disk IO profiles",
        "description": "Return a list of all disk IO profiles available to this organization",
        "tags": [
          "Disk IO profiles"
        ]
      }
    },
    "/organizations/organization/disk_backup_policies": {
      "get": {
        "operationId": "get:organization_disk_backup_policies",
        "summary": "List disk backup policies",
        "description": "Returns a list of all disk backup policies for a given organization\n## Scopes\n- `disk_backup_policies`\n- `disk_backup_policies:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk backup policies"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_backup_policies",
              "api.katapult.io/core/v1/disk_backup_policies:read"
            ]
          },
          {
            "Authenticator": [
              "disk_backup_policies",
              "disk_backup_policies:read"
            ]
          }
        ]
      }
    },
    "/virtual_machines/virtual_machine/disk_backup_policies": {
      "get": {
        "operationId": "get:virtual_machine_disk_backup_policies",
        "summary": "List disk backup policies for virtual machine",
        "description": "Returns a list of all disk backup policies for a given virtual machine\n## Scopes\n- `disk_backup_policies`\n- `disk_backup_policies:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk backup policies"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_backup_policies",
              "api.katapult.io/core/v1/disk_backup_policies:read"
            ]
          },
          {
            "Authenticator": [
              "disk_backup_policies",
              "disk_backup_policies:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:virtual_machine_disk_backup_policies",
        "summary": "Create disk backup policy for Virtual Machine",
        "description": "Creates a new disk backup policy for a virtual machine\n## Scopes\n- `disk_backup_policies`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk backup policies"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_backup_policies"
            ]
          },
          {
            "Authenticator": [
              "disk_backup_policies"
            ]
          }
        ]
      }
    },
    "/disks/disk/disk_backup_policies": {
      "get": {
        "operationId": "get:disk_disk_backup_policies",
        "summary": "List disk backup policies for disk",
        "description": "Returns a list of all disk backup policies for a given disk\n## Scopes\n- `disk_backup_policies`\n- `disk_backup_policies:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk backup policies"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_backup_policies",
              "api.katapult.io/core/v1/disk_backup_policies:read"
            ]
          },
          {
            "Authenticator": [
              "disk_backup_policies",
              "disk_backup_policies:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:disk_disk_backup_policies",
        "summary": "Create disk backup policy for disk",
        "description": "Creates a new disk backup policy for a disk\n## Scopes\n- `disk_backup_policies`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk backup policies"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_backup_policies"
            ]
          },
          {
            "Authenticator": [
              "disk_backup_policies"
            ]
          }
        ]
      }
    },
    "/disk_backup_policies/disk_backup_policy": {
      "get": {
        "operationId": "get:disk_backup_policy",
        "summary": "Get disk backup policy",
        "description": "Returns information about a specific disk backup policy\n## Scopes\n- `disk_backup_policies`\n- `disk_backup_policies:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk backup policies"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_backup_policies",
              "api.katapult.io/core/v1/disk_backup_policies:read"
            ]
          },
          {
            "Authenticator": [
              "disk_backup_policies",
              "disk_backup_policies:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:disk_backup_policy",
        "summary": "Delete disk backup policy",
        "description": "Deletes a disk backup policy and moves it to the trash\n## Scopes\n- `disk_backup_policies`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk backup policies"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_backup_policies"
            ]
          },
          {
            "Authenticator": [
              "disk_backup_policies"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:disk_backup_policy",
        "summary": "Update a disk backup policy",
        "description": "Updates the disk backup policy with the provided details\n## Scopes\n- `disk_backup_policies`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk backup policies"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_backup_policies"
            ]
          },
          {
            "Authenticator": [
              "disk_backup_policies"
            ]
          }
        ]
      }
    },
    "/disk_backup_policies/disk_backup_policy/schedule": {
      "delete": {
        "operationId": "delete:disk_backup_policy_schedule",
        "summary": "Schedule delete disk backup policy",
        "description": "Schedules a disk backup policy to be moved to the trash at a specific time. The backup policy will continue to function as normal until this time is reached.\n## Scopes\n- `disk_backup_policies`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk backup policies"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_backup_policies"
            ]
          },
          {
            "Authenticator": [
              "disk_backup_policies"
            ]
          }
        ]
      }
    },
    "/disk_templates/disk_template/versions": {
      "get": {
        "operationId": "get:disk_template_versions",
        "summary": "List disk template versions",
        "description": "Return a list of all disk template versions for a specific disk template\n## Scopes\n- `disk_templates`\n- `disk_templates:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk template versions"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_templates",
              "api.katapult.io/core/v1/disk_templates:read"
            ]
          },
          {
            "Authenticator": [
              "disk_templates",
              "disk_templates:read"
            ]
          }
        ]
      }
    },
    "/disk_template_versions/disk_template_version": {
      "get": {
        "operationId": "get:disk_template_version",
        "summary": "Get disk template version",
        "description": "Return details for a specific disk template version\n## Scopes\n- `disk_templates`\n- `disk_templates:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk template versions"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_templates",
              "api.katapult.io/core/v1/disk_templates:read"
            ]
          },
          {
            "Authenticator": [
              "disk_templates",
              "disk_templates:read"
            ]
          }
        ]
      }
    },
    "/disk_template_versions/disk_template_version/spec": {
      "get": {
        "operationId": "get:disk_template_version_spec",
        "summary": "Get disk template version spec",
        "description": "Return details provided by this template's specification\n## Scopes\n- `disk_templates`\n- `disk_templates:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk template versions"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_templates",
              "api.katapult.io/core/v1/disk_templates:read"
            ]
          },
          {
            "Authenticator": [
              "disk_templates",
              "disk_templates:read"
            ]
          }
        ]
      }
    },
    "/organizations/organization/disk_templates": {
      "get": {
        "operationId": "get:organization_disk_templates",
        "summary": "List disk templates",
        "description": "Return a list of all disk templates owned by an organization\n## Scopes\n- `disk_templates`\n- `disk_templates:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk templates"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_templates",
              "api.katapult.io/core/v1/disk_templates:read"
            ]
          },
          {
            "Authenticator": [
              "disk_templates",
              "disk_templates:read"
            ]
          }
        ]
      }
    },
    "/disk_templates/disk_template": {
      "get": {
        "operationId": "get:disk_template",
        "summary": "Get disk template",
        "description": "Return details for a specific disk template\n## Scopes\n- `disk_templates`\n- `disk_templates:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disk templates"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disk_templates",
              "api.katapult.io/core/v1/disk_templates:read"
            ]
          },
          {
            "Authenticator": [
              "disk_templates",
              "disk_templates:read"
            ]
          }
        ]
      }
    },
    "/organizations/organization/disks": {
      "get": {
        "operationId": "get:organization_disks",
        "summary": "List disks",
        "description": "Return a list of all disks owned by an organization\n## Scopes\n- `disks`\n- `disks:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disks",
              "api.katapult.io/core/v1/disks:read"
            ]
          },
          {
            "Authenticator": [
              "disks",
              "disks:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:organization_disks",
        "summary": "Create disk",
        "description": "Create a new disk for a given organization.\n## Scopes\n- `disks`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disks"
            ]
          },
          {
            "Authenticator": [
              "disks"
            ]
          }
        ]
      }
    },
    "/disks/disk": {
      "get": {
        "operationId": "get:disk",
        "summary": "Get disk",
        "description": "Return details for a specific disk\n## Scopes\n- `disks`\n- `disks:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disks",
              "api.katapult.io/core/v1/disks:read"
            ]
          },
          {
            "Authenticator": [
              "disks",
              "disks:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:disk",
        "summary": "Update disk",
        "description": "Update a disk for a given organization.\n## Scopes\n- `disks`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disks"
            ]
          },
          {
            "Authenticator": [
              "disks"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:disk",
        "summary": "Delete disk",
        "description": "Deletes a disk and moves it to the trash\n## Scopes\n- `disks`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disks"
            ]
          },
          {
            "Authenticator": [
              "disks"
            ]
          }
        ]
      }
    },
    "/disks/disk/assign": {
      "post": {
        "operationId": "post:disk_assign",
        "summary": "Assign disk to virtual machine",
        "description": "Assign a disk to a virtual machine.\n## Scopes\n- `disks`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disks"
            ]
          },
          {
            "Authenticator": [
              "disks"
            ]
          }
        ]
      }
    },
    "/disks/disk/unassign": {
      "post": {
        "operationId": "post:disk_unassign",
        "summary": "Unassign disk from virtual machine",
        "description": "Unassign a disk from a virtual machine.\n## Scopes\n- `disks`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disks"
            ]
          },
          {
            "Authenticator": [
              "disks"
            ]
          }
        ]
      }
    },
    "/disks/disk/attach": {
      "post": {
        "operationId": "post:disk_attach",
        "summary": "Attach disk to virtual machine",
        "description": "Attach a disk to its virtual machine.\n## Scopes\n- `disks`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disks"
            ]
          },
          {
            "Authenticator": [
              "disks"
            ]
          }
        ]
      }
    },
    "/disks/disk/detach": {
      "post": {
        "operationId": "post:disk_detach",
        "summary": "Detach disk from virtual machine",
        "description": "Detach a disk from its virtual machine.\n## Scopes\n- `disks`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disks"
            ]
          },
          {
            "Authenticator": [
              "disks"
            ]
          }
        ]
      }
    },
    "/disks/disk/resize": {
      "put": {
        "operationId": "put:disk_resize",
        "summary": "Resize disk",
        "description": "Resize a disk.\n## Scopes\n- `disks`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disks"
            ]
          },
          {
            "Authenticator": [
              "disks"
            ]
          }
        ]
      }
    },
    "/disks/disk/io_profile": {
      "put": {
        "operationId": "put:disk_io_profile",
        "summary": "Change disk IO profile",
        "description": "Change disk IO profile.\n## Scopes\n- `disks`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disks"
            ]
          },
          {
            "Authenticator": [
              "disks"
            ]
          }
        ]
      }
    },
    "/virtual_machines/virtual_machine/disks": {
      "get": {
        "operationId": "get:virtual_machine_disks",
        "summary": "List virtual machine disks",
        "description": "Return a list of all disks for a given virtual machine\n## Scopes\n- `disks`\n- `disks:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Disks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/disks",
              "api.katapult.io/core/v1/disks:read"
            ]
          },
          {
            "Authenticator": [
              "disks",
              "disks:read"
            ]
          }
        ]
      }
    },
    "/organizations/organization/file_storage_volumes": {
      "get": {
        "operationId": "get:organization_file_storage_volumes",
        "summary": "List file storage volumes",
        "description": "Returns a list of all file storage volumes for a given organization\n## Scopes\n- `file_storage_volumes`\n- `file_storage_volumes:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "File storage volumes"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/file_storage_volumes",
              "api.katapult.io/core/v1/file_storage_volumes:read"
            ]
          },
          {
            "Authenticator": [
              "file_storage_volumes",
              "file_storage_volumes:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:organization_file_storage_volumes",
        "summary": "Create file storage volume",
        "description": "Create a new file storage volume for a given organization.\n## Scopes\n- `file_storage_volumes`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "File storage volumes"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/file_storage_volumes"
            ]
          },
          {
            "Authenticator": [
              "file_storage_volumes"
            ]
          }
        ]
      }
    },
    "/file_storage_volumes/file_storage_volume": {
      "get": {
        "operationId": "get:file_storage_volume",
        "summary": "Get file storage volume",
        "description": "Returns details for a file storage volume.\n## Scopes\n- `file_storage_volumes`\n- `file_storage_volumes:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "File storage volumes"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/file_storage_volumes",
              "api.katapult.io/core/v1/file_storage_volumes:read"
            ]
          },
          {
            "Authenticator": [
              "file_storage_volumes",
              "file_storage_volumes:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:file_storage_volume",
        "summary": "Update file storage volume",
        "description": "Update a file storage volume with new properties.\n## Scopes\n- `file_storage_volumes`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "File storage volumes"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/file_storage_volumes"
            ]
          },
          {
            "Authenticator": [
              "file_storage_volumes"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:file_storage_volume",
        "summary": "Delete file storage volume",
        "description": "Delete a file storage volume.\n## Scopes\n- `file_storage_volumes`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "File storage volumes"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/file_storage_volumes"
            ]
          },
          {
            "Authenticator": [
              "file_storage_volumes"
            ]
          }
        ]
      }
    },
    "/gpu_types": {
      "get": {
        "operationId": "get:gpu_types",
        "summary": "List GPU types",
        "description": "Provides a full list of all GPU types",
        "tags": [
          "GPU types"
        ]
      }
    },
    "/gpu_types/gpu_type": {
      "get": {
        "operationId": "get:gpu_type",
        "summary": "Get GPU type",
        "description": "Provide details for a specific GPU type",
        "tags": [
          "GPU types"
        ]
      }
    },
    "/data_centers/data_center/gpu_types": {
      "get": {
        "operationId": "get:data_center_gpu_types",
        "summary": "List GPU types for Data Center",
        "description": "Provides a list of all GPU types available in a given data center",
        "tags": [
          "GPU types"
        ]
      }
    },
    "/organizations/organization/ip_addresses": {
      "get": {
        "operationId": "get:organization_ip_addresses",
        "summary": "List IP addresses",
        "description": "Returns a list of all IP addresses belonging to an organization\n## Scopes\n- `ip_addresses`\n- `ip_addresses:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "IP addresses"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/ip_addresses",
              "api.katapult.io/core/v1/ip_addresses:read"
            ]
          },
          {
            "Authenticator": [
              "ip_addresses",
              "ip_addresses:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:organization_ip_addresses",
        "summary": "Create IP Address",
        "description": "Creates a new IP address on this organization\n## Scopes\n- `ip_addresses`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "IP addresses"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/ip_addresses"
            ]
          },
          {
            "Authenticator": [
              "ip_addresses"
            ]
          }
        ]
      }
    },
    "/ip_addresses/ip_address": {
      "get": {
        "operationId": "get:ip_address",
        "summary": "Get IP address",
        "description": "Returns information about a specific IP address\n## Scopes\n- `ip_addresses`\n- `ip_addresses:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "IP addresses"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/ip_addresses",
              "api.katapult.io/core/v1/ip_addresses:read"
            ]
          },
          {
            "Authenticator": [
              "ip_addresses",
              "ip_addresses:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:ip_address",
        "summary": "Update IP address",
        "description": "Updates the details on an IP address\n## Scopes\n- `ip_addresses`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "IP addresses"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/ip_addresses"
            ]
          },
          {
            "Authenticator": [
              "ip_addresses"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:ip_address",
        "summary": "Release an IP address",
        "description": "Release an IP address from its organization\n## Scopes\n- `ip_addresses`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "IP addresses"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/ip_addresses"
            ]
          },
          {
            "Authenticator": [
              "ip_addresses"
            ]
          }
        ]
      }
    },
    "/ip_addresses/ip_address/unallocate": {
      "post": {
        "operationId": "post:ip_address_unallocate",
        "summary": "Unallocate an IP address",
        "description": "Unallocate an IP address from its resource\n## Scopes\n- `ip_addresses`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "IP addresses"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/ip_addresses"
            ]
          },
          {
            "Authenticator": [
              "ip_addresses"
            ]
          }
        ]
      }
    },
    "/load_balancers/load_balancer/rules": {
      "get": {
        "operationId": "get:load_balancer_rules",
        "summary": "List load balancer rules",
        "description": "Returns a list of all rules for a given load balancer\n## Scopes\n- `load_balancers`\n- `load_balancers:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Load balancer rules"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/load_balancers",
              "api.katapult.io/core/v1/load_balancers:read"
            ]
          },
          {
            "Authenticator": [
              "load_balancers",
              "load_balancers:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:load_balancer_rules",
        "summary": "Create load balancer rule",
        "description": "Create a new load balancer rule\n## Scopes\n- `load_balancers`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Load balancer rules"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/load_balancers"
            ]
          },
          {
            "Authenticator": [
              "load_balancers"
            ]
          }
        ]
      }
    },
    "/load_balancers/rules/load_balancer_rule": {
      "get": {
        "operationId": "get:load_balancers_rules_load_balancer_rule",
        "summary": "Get load balancer rule",
        "description": "Returns details about a load balancer rule\n## Scopes\n- `load_balancers`\n- `load_balancers:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Load balancer rules"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/load_balancers",
              "api.katapult.io/core/v1/load_balancers:read"
            ]
          },
          {
            "Authenticator": [
              "load_balancers",
              "load_balancers:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:load_balancers_rules_load_balancer_rule",
        "summary": "Update load balancer rule",
        "description": "Updates a load balancer rule with new properties\n## Scopes\n- `load_balancers`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Load balancer rules"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/load_balancers"
            ]
          },
          {
            "Authenticator": [
              "load_balancers"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:load_balancers_rules_load_balancer_rule",
        "summary": "Delete load balancer rule",
        "description": "Delete a load balancer rule\n## Scopes\n- `load_balancers`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Load balancer rules"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/load_balancers"
            ]
          },
          {
            "Authenticator": [
              "load_balancers"
            ]
          }
        ]
      }
    },
    "/organizations/organization/load_balancers": {
      "get": {
        "operationId": "get:organization_load_balancers",
        "summary": "List load balancers",
        "description": "Returns a list of all load balancers for a given organization\n## Scopes\n- `load_balancers`\n- `load_balancers:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Load balancers"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/load_balancers",
              "api.katapult.io/core/v1/load_balancers:read"
            ]
          },
          {
            "Authenticator": [
              "load_balancers",
              "load_balancers:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:organization_load_balancers",
        "summary": "Create load balancer",
        "description": "Create a new load balancer for a given organization\n## Scopes\n- `load_balancers`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Load balancers"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/load_balancers"
            ]
          },
          {
            "Authenticator": [
              "load_balancers"
            ]
          }
        ]
      }
    },
    "/load_balancers/load_balancer": {
      "get": {
        "operationId": "get:load_balancer",
        "summary": "Get load balancer",
        "description": "Returns details about a load balancer\n## Scopes\n- `load_balancers`\n- `load_balancers:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Load balancers"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/load_balancers",
              "api.katapult.io/core/v1/load_balancers:read"
            ]
          },
          {
            "Authenticator": [
              "load_balancers",
              "load_balancers:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:load_balancer",
        "summary": "Update load balancer",
        "description": "Updates a load balancer with new properties\n## Scopes\n- `load_balancers`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Load balancers"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/load_balancers"
            ]
          },
          {
            "Authenticator": [
              "load_balancers"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:load_balancer",
        "summary": "Delete load balancer",
        "description": "Delete a load balancer\n## Scopes\n- `load_balancers`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Load balancers"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/load_balancers"
            ]
          },
          {
            "Authenticator": [
              "load_balancers"
            ]
          }
        ]
      }
    },
    "/organizations/organization/managed": {
      "get": {
        "operationId": "get:organization_managed",
        "summary": "List managed organizations",
        "description": "List all managed organizations owned by the given organization\n## Scopes\n- `managed_organizations`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Managed organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/managed_organizations"
            ]
          },
          {
            "Authenticator": [
              "managed_organizations"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:organization_managed",
        "summary": "Create managed organization",
        "description": "Create a new managed organization within an existing organization\n## Scopes\n- `managed_organizations`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Managed organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/managed_organizations"
            ]
          },
          {
            "Authenticator": [
              "managed_organizations"
            ]
          }
        ]
      }
    },
    "/managed_organizations/organization": {
      "delete": {
        "operationId": "delete:organization",
        "summary": "Delete managed organization",
        "description": "Delete a managed organization. All resources must be removed first.\n## Scopes\n- `managed_organizations:delete`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Managed organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/managed_organizations:delete"
            ]
          },
          {
            "Authenticator": [
              "managed_organizations:delete"
            ]
          }
        ]
      }
    },
    "/organizations/organization/network_speed_profiles": {
      "get": {
        "operationId": "get:organization_network_speed_profiles",
        "summary": "List network speed profiles",
        "description": "Returns a list of all network speed profiles available to an organization",
        "tags": [
          "Network speed profiles"
        ]
      }
    },
    "/organizations/organization/available_networks": {
      "get": {
        "operationId": "get:organization_available_networks",
        "summary": "List networks",
        "description": "Returns a list of all networks available for an organization",
        "tags": [
          "Networks"
        ]
      }
    },
    "/networks/network": {
      "get": {
        "operationId": "get:network",
        "summary": "Get Network",
        "description": "Returns details for a specific network",
        "tags": [
          "Networks"
        ]
      }
    },
    "/organizations/organization/object_storage/object_storage_cluster": {
      "post": {
        "operationId": "post:organization_object_storage_object_storage_cluster",
        "summary": "Create object storage account",
        "description": "Create a new object storage account for an organization. Provisioning will be started in the background and can be monitored via the GET account endpoint.\n## Scopes\n- `object_storage`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Object storage"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage"
            ]
          },
          {
            "Authenticator": [
              "object_storage"
            ]
          }
        ]
      },
      "get": {
        "operationId": "get:organization_object_storage_object_storage_cluster",
        "summary": "Get object storage account details",
        "description": "Returns object storage account details\n## Scopes\n- `object_storage:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Object storage"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage:read"
            ]
          },
          {
            "Authenticator": [
              "object_storage:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:organization_object_storage_object_storage_cluster",
        "summary": "Move object storage to trash",
        "description": "Move object storage into the trash\n## Scopes\n- `object_storage`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Object storage"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/object_storage"
            ]
          },
          {
            "Authenticator": [
              "object_storage"
            ]
          }
        ]
      }
    },
    "/operating_systems": {
      "get": {
        "operationId": "get:operating_systems",
        "summary": "List operating systems",
        "description": "Return a list of all operating systems",
        "tags": [
          "Operating systems"
        ]
      }
    },
    "/operating_systems/operating_system": {
      "get": {
        "operationId": "get:operating_system",
        "summary": "Get operating system",
        "description": "Return details for a specific operating system",
        "tags": [
          "Operating systems"
        ]
      }
    },
    "/organizations/organization/users_with_access": {
      "get": {
        "operationId": "get:organization_users_with_access",
        "summary": "List organization users",
        "description": "This will return a simple list of users with any access to this organization. This\nendpoint is available to all users with access to the organization therefore allows\nthem to see a small amount of information about their peers. This is useful when\ncombined with other API actions that require the ID of a fellow user (such as when\ndetermining which users to assign a virtual machine).\n\n## Scopes\n- `organizations:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentica[...]",
        "tags": [
          "Organization users"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/organizations:read"
            ]
          },
          {
            "Authenticator": [
              "organizations:read"
            ]
          }
        ]
      }
    },
    "/organizations": {
      "get": {
        "operationId": "get:organizations",
        "summary": "List organizations",
        "description": "This will return a list of all organizations the authenticated identity has access to\n## Scopes\n- `organizations:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/organizations:read"
            ]
          },
          {
            "Authenticator": [
              "organizations:read"
            ]
          }
        ]
      }
    },
    "/organizations/organization": {
      "get": {
        "operationId": "get:organization",
        "summary": "Get organization",
        "description": "Returns information about a specific organization\n## Scopes\n- `organizations:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/organizations:read"
            ]
          },
          {
            "Authenticator": [
              "organizations:read"
            ]
          }
        ]
      }
    },
    "/organizations/organization/policy": {
      "get": {
        "operationId": "get:organization_policy",
        "summary": "Get organization limits and usage",
        "description": "Returns the computed policy limits for a organization\n## Scopes\n- `organizations:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/organizations:read"
            ]
          },
          {
            "Authenticator": [
              "organizations:read"
            ]
          }
        ]
      }
    },
    "/organizations/organization/policy_limits": {
      "get": {
        "operationId": "get:organization_policy_limits",
        "summary": "Get organization policy limits",
        "description": "Returns the computed policy limits for a organization\n## Scopes\n- `organizations:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/organizations:read"
            ]
          },
          {
            "Authenticator": [
              "organizations:read"
            ]
          }
        ]
      }
    },
    "/organizations/organization/prices": {
      "get": {
        "operationId": "get:organization_prices",
        "summary": "Get organization prices",
        "description": "Returns the active prices for an organization\n## Scopes\n- `organizations:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/organizations:read"
            ]
          },
          {
            "Authenticator": [
              "organizations:read"
            ]
          }
        ]
      }
    },
    "/organizations/organization/deletion_steps": {
      "get": {
        "operationId": "get:organization_deletion_steps",
        "summary": "Deletion steps",
        "description": "Returns details of the steps which must be performed before an organization can be deleted\n## Scopes\n- `organizations:delete`\n- `managed_organizations:delete`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/organizations:delete",
              "api.katapult.io/core/v1/managed_organizations:delete"
            ]
          },
          {
            "Authenticator": [
              "organizations:delete",
              "managed_organizations:delete"
            ]
          }
        ]
      }
    },
    "/virtual_machines/virtual_machine/start": {
      "post": {
        "operationId": "post:virtual_machine_start",
        "summary": "Start virtual machine",
        "description": "Queues a task to start a virtual machine\n## Scopes\n- `virtual_machines`\n- `virtual_machines:power_actions`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Power functions"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:power_actions"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:power_actions"
            ]
          }
        ]
      }
    },
    "/virtual_machines/virtual_machine/stop": {
      "post": {
        "operationId": "post:virtual_machine_stop",
        "summary": "Stop virtual machine",
        "description": "Queues a task to stop a virtual machine\n## Scopes\n- `virtual_machines`\n- `virtual_machines:power_actions`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Power functions"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:power_actions"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:power_actions"
            ]
          }
        ]
      }
    },
    "/virtual_machines/virtual_machine/shutdown": {
      "post": {
        "operationId": "post:virtual_machine_shutdown",
        "summary": "Shutdown virtual machine",
        "description": "Queues a task to shutdown a virtual machine\n## Scopes\n- `virtual_machines`\n- `virtual_machines:power_actions`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Power functions"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:power_actions"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:power_actions"
            ]
          }
        ]
      }
    },
    "/virtual_machines/virtual_machine/reset": {
      "post": {
        "operationId": "post:virtual_machine_reset",
        "summary": "Reset virtual machine",
        "description": "Queues a task to reset a virtual machine\n## Scopes\n- `virtual_machines`\n- `virtual_machines:power_actions`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Power functions"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:power_actions"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:power_actions"
            ]
          }
        ]
      }
    },
    "/dns_zones/dns_zone/records": {
      "get": {
        "operationId": "get:dns_zone_records",
        "summary": "List DNS records",
        "description": "Return a list of all DNS records in a zone\n## Scopes\n- `dns`\n- `dns:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Records"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/dns",
              "api.katapult.io/core/v1/dns:read"
            ]
          },
          {
            "Authenticator": [
              "dns",
              "dns:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:dns_zone_records",
        "summary": "Create DNS record",
        "description": "Create a new DNS record\n## Scopes\n- `dns`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Records"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/dns"
            ]
          },
          {
            "Authenticator": [
              "dns"
            ]
          }
        ]
      }
    },
    "/dns_records/dns_record": {
      "get": {
        "operationId": "get:dns_record",
        "summary": "Get DNS record",
        "description": "Return details for a specific DNS record\n## Scopes\n- `dns`\n- `dns:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Records"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/dns",
              "api.katapult.io/core/v1/dns:read"
            ]
          },
          {
            "Authenticator": [
              "dns",
              "dns:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:dns_record",
        "summary": "Update DNS record",
        "description": "Update a DNS record properties\n## Scopes\n- `dns`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Records"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/dns"
            ]
          },
          {
            "Authenticator": [
              "dns"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:dns_record",
        "summary": "Delete DNS record",
        "description": "Delete a DNS record\n## Scopes\n- `dns`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Records"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/dns"
            ]
          },
          {
            "Authenticator": [
              "dns"
            ]
          }
        ]
      }
    },
    "/organizations/organization/ssh_keys": {
      "get": {
        "operationId": "get:organization_ssh_keys",
        "summary": "List organization SSH keys",
        "description": "Returns a list of all SSH keys for an organization",
        "tags": [
          "SSH keys"
        ]
      },
      "post": {
        "operationId": "post:organization_ssh_keys",
        "summary": "Add organization SSH key",
        "description": "Add an SSH key to an organization",
        "tags": [
          "SSH keys"
        ]
      }
    },
    "/ssh_keys/ssh_key": {
      "delete": {
        "operationId": "delete:ssh_key",
        "summary": "Delete SSH key",
        "description": "Delete an SSH key",
        "tags": [
          "SSH keys"
        ]
      }
    },
    "/security_groups/security_group/rules": {
      "get": {
        "operationId": "get:security_group_rules",
        "summary": "List security group rules",
        "description": "Returns a list of all rules for a given security group\n## Scopes\n- `security_groups`\n- `security_groups:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Security group rules"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/security_groups",
              "api.katapult.io/core/v1/security_groups:read"
            ]
          },
          {
            "Authenticator": [
              "security_groups",
              "security_groups:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:security_group_rules",
        "summary": "Create security group rule",
        "description": "Create a new security group rule\n## Scopes\n- `security_groups`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Security group rules"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/security_groups"
            ]
          },
          {
            "Authenticator": [
              "security_groups"
            ]
          }
        ]
      }
    },
    "/security_groups/rules/security_group_rule": {
      "get": {
        "operationId": "get:security_groups_rules_security_group_rule",
        "summary": "Get security group rule",
        "description": "Returns details about a security group rule\n## Scopes\n- `security_groups`\n- `security_groups:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Security group rules"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/security_groups",
              "api.katapult.io/core/v1/security_groups:read"
            ]
          },
          {
            "Authenticator": [
              "security_groups",
              "security_groups:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:security_groups_rules_security_group_rule",
        "summary": "Update security group rule",
        "description": "Updates a security group rule with new properties\n## Scopes\n- `security_groups`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Security group rules"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/security_groups"
            ]
          },
          {
            "Authenticator": [
              "security_groups"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:security_groups_rules_security_group_rule",
        "summary": "Delete security group rule",
        "description": "Delete a security group rule\n## Scopes\n- `security_groups`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Security group rules"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/security_groups"
            ]
          },
          {
            "Authenticator": [
              "security_groups"
            ]
          }
        ]
      }
    },
    "/organizations/organization/security_groups": {
      "get": {
        "operationId": "get:organization_security_groups",
        "summary": "List security groups",
        "description": "Returns a list of all security groups for a given organization\n## Scopes\n- `security_groups`\n- `security_groups:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Security groups"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/security_groups",
              "api.katapult.io/core/v1/security_groups:read"
            ]
          },
          {
            "Authenticator": [
              "security_groups",
              "security_groups:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:organization_security_groups",
        "summary": "Create security group",
        "description": "Create a new security group for a given organization\n## Scopes\n- `security_groups`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Security groups"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/security_groups"
            ]
          },
          {
            "Authenticator": [
              "security_groups"
            ]
          }
        ]
      }
    },
    "/security_groups/security_group": {
      "get": {
        "operationId": "get:security_group",
        "summary": "Get security group",
        "description": "Returns details about a security group\n## Scopes\n- `security_groups`\n- `security_groups:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Security groups"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/security_groups",
              "api.katapult.io/core/v1/security_groups:read"
            ]
          },
          {
            "Authenticator": [
              "security_groups",
              "security_groups:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:security_group",
        "summary": "Update security group",
        "description": "Updates a security group with new properties\n## Scopes\n- `security_groups`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Security groups"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/security_groups"
            ]
          },
          {
            "Authenticator": [
              "security_groups"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:security_group",
        "summary": "Delete security group",
        "description": "Delete a security group\n## Scopes\n- `security_group`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Security groups"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/security_group"
            ]
          },
          {
            "Authenticator": [
              "security_group"
            ]
          }
        ]
      }
    },
    "/organizations/organization/tags": {
      "get": {
        "operationId": "get:organization_tags",
        "summary": "List tags",
        "description": "Returns a list of all tags for an organization\n## Scopes\n- `tags`\n- `tags:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Tags"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/tags",
              "api.katapult.io/core/v1/tags:read"
            ]
          },
          {
            "Authenticator": [
              "tags",
              "tags:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:organization_tags",
        "summary": "Create a tag",
        "description": "Creates a new tag with the provided properties\n## Scopes\n- `tags`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Tags"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/tags"
            ]
          },
          {
            "Authenticator": [
              "tags"
            ]
          }
        ]
      }
    },
    "/tags/tag": {
      "get": {
        "operationId": "get:tag",
        "summary": "Get tag",
        "description": "Returns details about a specific tag\n## Scopes\n- `tags`\n- `tags:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Tags"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/tags",
              "api.katapult.io/core/v1/tags:read"
            ]
          },
          {
            "Authenticator": [
              "tags",
              "tags:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:tag",
        "summary": "Update a tag",
        "description": "Updates a tag with the provided properties\n## Scopes\n- `tags`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Tags"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/tags"
            ]
          },
          {
            "Authenticator": [
              "tags"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:tag",
        "summary": "Delete a tag",
        "description": "Deletes a tag\n## Scopes\n- `tags`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Tags"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/tags"
            ]
          },
          {
            "Authenticator": [
              "tags"
            ]
          }
        ]
      }
    },
    "/tasks/task": {
      "get": {
        "operationId": "get:task",
        "summary": "Get Task",
        "description": "Returns details about a specific task\n## Scopes\n- `tasks`\n- `tasks:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Tasks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/tasks",
              "api.katapult.io/core/v1/tasks:read"
            ]
          },
          {
            "Authenticator": [
              "tasks",
              "tasks:read"
            ]
          }
        ]
      }
    },
    "/organizations/organization/trash_objects": {
      "get": {
        "operationId": "get:organization_trash_objects",
        "summary": "List trash objects",
        "description": "Provides a full list of all trash objects for a specific organization\n## Scopes\n- `trash_objects:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Trash objects"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/trash_objects:read"
            ]
          },
          {
            "Authenticator": [
              "trash_objects:read"
            ]
          }
        ]
      }
    },
    "/organizations/organization/trash_objects/purge_all": {
      "post": {
        "operationId": "post:organization_trash_objects_purge_all",
        "summary": "Purge all trash objects",
        "description": "Purge all trash objects for an organization\n## Scopes\n- `trash_objects:purge`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Trash objects"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/trash_objects:purge"
            ]
          },
          {
            "Authenticator": [
              "trash_objects:purge"
            ]
          }
        ]
      }
    },
    "/trash_objects/trash_object": {
      "get": {
        "operationId": "get:trash_object",
        "summary": "Get trash object",
        "description": "Provides information on a specific trash object\n## Scopes\n- `trash_objects:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Trash objects"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/trash_objects:read"
            ]
          },
          {
            "Authenticator": [
              "trash_objects:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:trash_object",
        "summary": "Purge a trash object",
        "description": "Purge a specific trash object\n## Scopes\n- `trash_objects:purge`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Trash objects"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/trash_objects:purge"
            ]
          },
          {
            "Authenticator": [
              "trash_objects:purge"
            ]
          }
        ]
      }
    },
    "/trash_objects/trash_object/restore": {
      "post": {
        "operationId": "post:trash_object_restore",
        "summary": "Restore a trash object",
        "description": "Restore a trashed object to its original location\n## Scopes\n- `trash_objects:restore`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Trash objects"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/trash_objects:restore"
            ]
          },
          {
            "Authenticator": [
              "trash_objects:restore"
            ]
          }
        ]
      }
    },
    "/users/current": {
      "get": {
        "operationId": "get:users_current",
        "summary": "Get current user details",
        "description": "This endpoint returns details for the currently authenticated user. If the API token used to\nauthenticate to the API is not associated with a user, this method will return an error.\n",
        "tags": [
          "Users"
        ]
      }
    },
    "/invalidate_linked_web_session": {
      "post": {
        "operationId": "post:invalidate_linked_web_session",
        "summary": "Invalidate linked web session",
        "description": "This endpoint allows you to invalidate the web session which is associated with your authenticated\nidentity. This will only work for API identities (most likely API tokens) that were generated using the first-party application\nlogin flow.\n",
        "tags": [
          "Users"
        ]
      }
    },
    "/organizations/organization/virtual_networks": {
      "get": {
        "operationId": "get:organization_virtual_networks",
        "summary": "List virtual networks",
        "description": "Return a list of all virtual networks for an organization\n## Scopes\n- `virtual_networks`\n- `virtual_networks:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual Networks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_networks",
              "api.katapult.io/core/v1/virtual_networks:read"
            ]
          },
          {
            "Authenticator": [
              "virtual_networks",
              "virtual_networks:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:organization_virtual_networks",
        "summary": "Create a virtual network",
        "description": "Create a new virtual network with the provided details\n## Scopes\n- `virtual_networks`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual Networks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_networks"
            ]
          },
          {
            "Authenticator": [
              "virtual_networks"
            ]
          }
        ]
      }
    },
    "/virtual_networks/virtual_network": {
      "get": {
        "operationId": "get:virtual_network",
        "summary": "Get virtual network",
        "description": "Return detailed information about a virtual network\n## Scopes\n- `virtual_networks`\n- `virtual_networks:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual Networks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_networks",
              "api.katapult.io/core/v1/virtual_networks:read"
            ]
          },
          {
            "Authenticator": [
              "virtual_networks",
              "virtual_networks:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:virtual_network",
        "summary": "Update a virtual network",
        "description": "Update a virtual network with the provided details\n## Scopes\n- `virtual_networks`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual Networks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_networks"
            ]
          },
          {
            "Authenticator": [
              "virtual_networks"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:virtual_network",
        "summary": "Delete a virtual network",
        "description": "\n## Scopes\n- `virtual_networks`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual Networks"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_networks"
            ]
          },
          {
            "Authenticator": [
              "virtual_networks"
            ]
          }
        ]
      }
    },
    "/organizations/organization/virtual_machine_groups": {
      "get": {
        "operationId": "get:organization_virtual_machine_groups",
        "summary": "List virtual machine groups",
        "description": "Return a list of all virtual machine groups for an organization\n## Scopes\n- `virtual_machine_groups`\n- `virtual_machine_groups:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine groups"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machine_groups",
              "api.katapult.io/core/v1/virtual_machine_groups:read"
            ]
          },
          {
            "Authenticator": [
              "virtual_machine_groups",
              "virtual_machine_groups:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:organization_virtual_machine_groups",
        "summary": "Create a virtual machine group",
        "description": "Create a new virtual machine group with the provided details\n## Scopes\n- `virtual_machine_groups`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine groups"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machine_groups"
            ]
          },
          {
            "Authenticator": [
              "virtual_machine_groups"
            ]
          }
        ]
      }
    },
    "/virtual_machine_groups/virtual_machine_group": {
      "get": {
        "operationId": "get:virtual_machine_group",
        "summary": "Get virtual machine group",
        "description": "Return detailed information about a virtual machine group\n## Scopes\n- `virtual_machine_groups`\n- `virtual_machine_groups:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine groups"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machine_groups",
              "api.katapult.io/core/v1/virtual_machine_groups:read"
            ]
          },
          {
            "Authenticator": [
              "virtual_machine_groups",
              "virtual_machine_groups:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:virtual_machine_group",
        "summary": "Update a virtual machine group",
        "description": "Update a virtual machine group with the provided details\n## Scopes\n- `virtual_machine_groups`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine groups"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machine_groups"
            ]
          },
          {
            "Authenticator": [
              "virtual_machine_groups"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:virtual_machine_group",
        "summary": "Delete a virtual machine group",
        "description": "\n## Scopes\n- `virtual_machine_groups`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine groups"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machine_groups"
            ]
          },
          {
            "Authenticator": [
              "virtual_machine_groups"
            ]
          }
        ]
      }
    },
    "/virtual_machines/virtual_machine/network_interfaces": {
      "get": {
        "operationId": "get:virtual_machine_network_interfaces",
        "summary": "List virtual machine network interfaces",
        "description": "Returns a list of virtual machine network interfaces\n## Scopes\n- `virtual_machines`\n- `virtual_machines:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine network interfaces"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:read"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "post:virtual_machine_network_interfaces",
        "summary": "Create a virtual network interface",
        "description": "Create a new virtual machine network interface with the provided details\n## Scopes\n- `virtual_machines`\n- `virtual_machines:network_interfaces`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine network interfaces"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:network_interfaces"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:network_interfaces"
            ]
          }
        ]
      }
    },
    "/virtual_machines/virtual_machine/networks/network/interface": {
      "get": {
        "operationId": "get:virtual_machine_network_interface",
        "summary": "Get virtual machine network interface by network",
        "description": "Return information about a virtual machine network interface for a specific network\n## Scopes\n- `virtual_machines`\n- `virtual_machines:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine network interfaces"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:read"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:read"
            ]
          }
        ]
      }
    },
    "/virtual_machine_network_interfaces/virtual_machine_network_interface": {
      "get": {
        "operationId": "get:v_m_n_i__v_m_n_i",
        "summary": "Get virtual machine network interface",
        "description": "Return information about a given virtual machine network interface\n## Scopes\n- `virtual_machines`\n- `virtual_machines:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine network interfaces"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:read"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:virtual_machine_network_interface",
        "summary": "Delete a virtual machine network interface",
        "description": "\n## Scopes\n- `virtual_machines`\n- `virtual_machines:network_interfaces`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine network interfaces"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:network_interfaces"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:network_interfaces"
            ]
          }
        ]
      }
    },
    "/virtual_machine_network_interfaces/virtual_machine_network_interface/available_ips/address_version": {
      "get": {
        "operationId": "get:virtual_machine_network_interface_available_ips_address_version",
        "summary": "Get addresses available for network interface",
        "description": "Returns a list of IP addresses that can be allocated to a specific network interface\n## Scopes\n- `ip_addresses`\n- `ip_addresses:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine network interfaces"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/ip_addresses",
              "api.katapult.io/core/v1/ip_addresses:read"
            ]
          },
          {
            "Authenticator": [
              "ip_addresses",
              "ip_addresses:read"
            ]
          }
        ]
      }
    },
    "/virtual_machine_network_interfaces/virtual_machine_network_interface/allocate_ip": {
      "post": {
        "operationId": "post:virtual_machine_network_interface_allocate_ip",
        "summary": "Allocate an IP address",
        "description": "Allocate a specific IP address to a given network interface\n## Scopes\n- `ip_addresses`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine network interfaces"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/ip_addresses"
            ]
          },
          {
            "Authenticator": [
              "ip_addresses"
            ]
          }
        ]
      }
    },
    "/virtual_machine_network_interfaces/virtual_machine_network_interface/allocate_new_ip": {
      "post": {
        "operationId": "post:virtual_machine_network_interface_allocate_new_ip",
        "summary": "Allocate a new IP address",
        "description": "Add a new IP address to this organization and allocate it to a virtual machine network interface\n## Scopes\n- `ip_addresses`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine network interfaces"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/ip_addresses"
            ]
          },
          {
            "Authenticator": [
              "ip_addresses"
            ]
          }
        ]
      }
    },
    "/virtual_machine_network_interfaces/virtual_machine_network_interface/update_speed_profile": {
      "patch": {
        "operationId": "patch:virtual_machine_network_interface_update_speed_profile",
        "summary": "Update the network speed profile for a virtual machine network interface",
        "description": "\n## Scopes\n- `virtual_machines`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine network interfaces"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines"
            ]
          }
        ]
      }
    },
    "/virtual_machine_network_interfaces/virtual_machine_network_interface/attach": {
      "post": {
        "operationId": "post:virtual_machine_network_interface_attach",
        "summary": "Attach to virtual machine",
        "description": "Attach a network interface to a virtual machine.\n## Scopes\n- `virtual_machines`\n- `virtual_machines:network_interfaces`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine network interfaces"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:network_interfaces"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:network_interfaces"
            ]
          }
        ]
      }
    },
    "/virtual_machine_network_interfaces/virtual_machine_network_interface/detach": {
      "post": {
        "operationId": "post:virtual_machine_network_interface_detach",
        "summary": "Detach from virtual machine",
        "description": "Detach a network interface from its virtual machine.\n## Scopes\n- `virtual_machines`\n- `virtual_machines:network_interfaces`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine network interfaces"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:network_interfaces"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:network_interfaces"
            ]
          }
        ]
      }
    },
    "/virtual_machine_packages": {
      "get": {
        "operationId": "get:virtual_machine_packages",
        "summary": "List virtual machine packages",
        "description": "Returns a list of virtual machine packages\n## Scopes\n- `virtual_machine_packages:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine packages"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machine_packages:read"
            ]
          },
          {
            "Authenticator": [
              "virtual_machine_packages:read"
            ]
          }
        ]
      }
    },
    "/virtual_machine_packages/virtual_machine_package": {
      "get": {
        "operationId": "get:virtual_machine_package",
        "summary": "Get virtual machine package",
        "description": "Return information about a given virtual machine package\n## Scopes\n- `virtual_machine_packages:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machine packages"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machine_packages:read"
            ]
          },
          {
            "Authenticator": [
              "virtual_machine_packages:read"
            ]
          }
        ]
      }
    },
    "/organizations/organization/virtual_machines": {
      "get": {
        "operationId": "get:organization_virtual_machines",
        "summary": "List virtual machines",
        "description": "Returns a list of all virtual machines for a given organization\n## Scopes\n- `virtual_machines`\n- `virtual_machines:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machines"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:read"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:read"
            ]
          }
        ]
      }
    },
    "/virtual_machines/virtual_machine": {
      "get": {
        "operationId": "get:virtual_machine",
        "summary": "Get virtual machine",
        "description": "Return information about a virtual machine\n## Scopes\n- `virtual_machines`\n- `virtual_machines:read`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machines"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines",
              "api.katapult.io/core/v1/virtual_machines:read"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines",
              "virtual_machines:read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patch:virtual_machine",
        "summary": "Update a Virtual Machine",
        "description": "Update the properties of a virtual machine\n## Scopes\n- `virtual_machines`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machines"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete:virtual_machine",
        "summary": "Delete virtual machine",
        "description": "Moves an existing virtual machine to the trash\n## Scopes\n- `virtual_machines`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machines"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines"
            ]
          }
        ]
      }
    },
    "/virtual_machines/virtual_machine/package": {
      "put": {
        "operationId": "put:virtual_machine_package",
        "summary": "Change package",
        "description": "Change a package for a virtual machine\n## Scopes\n- `virtual_machines`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machines"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines"
            ]
          }
        ]
      }
    },
    "/virtual_machines/virtual_machine/flexible_resources": {
      "put": {
        "operationId": "put:virtual_machine_flexible_resources",
        "summary": "Change flexible resources",
        "description": "Change the flexible resources assigned to a virtual machine\n## Scopes\n- `virtual_machines`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machines"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines"
            ]
          }
        ]
      }
    },
    "/virtual_machines/virtual_machine/allocate_ip": {
      "post": {
        "operationId": "post:virtual_machine_allocate_ip",
        "summary": "Allocate an IP Address",
        "description": "Allocate an IP address to a virtual machine, automatically determining the network interface\n## Scopes\n- `ip_addresses`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machines"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/ip_addresses"
            ]
          },
          {
            "Authenticator": [
              "ip_addresses"
            ]
          }
        ]
      }
    },
    "/virtual_machine/authorized_keys": {
      "get": {
        "operationId": "get:virtual_machine_authorized_keys",
        "summary": "Get authorized keys for a virtual machine",
        "description": "Return the authorized keys for the virtual machine associated with the provided API token\n## Scopes\n- `virtual_machines:authorized_keys`\n\n### OAuth2 Scopes\nWhen using OAuth2 authentication, scopes are prefixed with `api.katapult.io/core/v1/`.\n",
        "tags": [
          "Virtual machines"
        ],
        "security": [
          {
            "OAuth2": [
              "api.katapult.io/core/v1/virtual_machines:authorized_keys"
            ]
          },
          {
            "Authenticator": [
              "virtual_machines:authorized_keys"
            ]
          }
        ]
      }
    },
    "/zones": {
      "get": {
        "operationId": "get:zones",
        "summary": "List zones",
        "description": "Returns a list of all zones on the system for the current identity",
        "tags": [
          "Zones"
        ]
      }
    },
    "/zones/zone": {
      "get": {
        "operationId": "get:zone",
        "summary": "Get zone",
        "description": "Returns the details for a specific zone",
        "tags": [
          "Zones"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "x-scope-prefix": "api.katapult.io/core/v1/",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://identity.krystal.io/oauth2/auth",
            "tokenUrl": "https://identity.krystal.io/oauth2/token",
            "refreshUrl": "https://identity.krystal.io/oauth2/token",
            "scopes": {
              "api.katapult.io/core/v1/address_lists": "Manage address lists",
              "api.katapult.io/core/v1/address_lists:read": "Read-only access to address lists",
              "api.katapult.io/core/v1/api_tokens": "Manage API tokens",
              "api.katapult.io/core/v1/api_tokens:read": "Read-only access to API tokens",
              "api.katapult.io/core/v1/disk_backup_policies": "Manage disk backup policies",
              "api.katapult.io/core/v1/disk_backup_policies:read": "Read-only access to disk backup policies",
              "api.katapult.io/core/v1/certificates:read": "Read-only access to certificates",
              "api.katapult.io/core/v1/disks": "Manage disks",
              "api.katapult.io/core/v1/disks:read": "Read-only access to disks",
              "api.katapult.io/core/v1/disk_templates": "Manage disk templates",
              "api.katapult.io/core/v1/disk_templates:read": "Read-only access to disk templates",
              "api.katapult.io/core/v1/file_storage_volumes": "Manage file storage volumes",
              "api.katapult.io/core/v1/file_storage_volumes:read": "Read-only access to file storage volumes",
              "api.katapult.io/core/v1/ip_addresses": "Manage IP addresses",
              "api.katapult.io/core/v1/ip_addresses:read": "Read-only access to IP addresses",
              "api.katapult.io/core/v1/object_storage": "Manage object storage",
              "api.katapult.io/core/v1/object_storage:read": "Read-only access to object storage",
              "api.katapult.io/core/v1/organizations:read": "Read-only access to organizations",
              "api.katapult.io/core/v1/organizations:delete": "Delete organizations",
              "api.katapult.io/core/v1/managed_organizations": "Manage managed organizations",
              "api.katapult.io/core/v1/managed_organizations:delete": "Delete managed organizations",
              "api.katapult.io/core/v1/security_groups": "Manage security groups",
              "api.katapult.io/core/v1/security_groups:read": "Read-only access to security groups",
              "api.katapult.io/core/v1/tags": "Manage tags",
              "api.katapult.io/core/v1/tags:read": "Read-only access to tags",
              "api.katapult.io/core/v1/tasks:read": "Read-only access to tasks",
              "api.katapult.io/core/v1/trash_objects:read": "Read-only access to objects in the trash",
              "api.katapult.io/core/v1/trash_objects:purge": "Purge items from the trash",
              "api.katapult.io/core/v1/trash_objects:restore": "Restore items from the trash",
              "api.katapult.io/core/v1/dns": "Manage DNS zones/records",
              "api.katapult.io/core/v1/dns:read": "Read-only access to DNS zones/records",
              "api.katapult.io/core/v1/load_balancers": "Manage load balancers",
              "api.katapult.io/core/v1/load_balancers:read": "Read-only access to load balancers",
              "api.katapult.io/core/v1/virtual_machines": "Manage virtual machines",
              "api.katapult.io/core/v1/virtual_machines:read": "Read-only access to virtual machines",
              "api.katapult.io/core/v1/virtual_machines:power_actions": "Start & stop virtual machines",
              "api.katapult.io/core/v1/virtual_machines:console": "Access virtual machine consoles",
              "api.katapult.io/core/v1/virtual_machines:authorized_keys": "Access virtual machine authorized keys",
              "api.katapult.io/core/v1/virtual_machines:network_interfaces": "Access virtual machine network interfaces",
              "api.katapult.io/core/v1/virtual_machine_groups": "Manage virtual machine groups",
              "api.katapult.io/core/v1/virtual_machine_groups:read": "Read-only access to virtual machine groups",
              "api.katapult.io/core/v1/virtual_networks": "Manage virtual networks",
              "api.katapult.io/core/v1/virtual_networks:read": "Read-only access to virtual networks"
            }
          }
        }
      },
      "Authenticator": {
        "scheme": "bearer",
        "type": "http"
      }
    }
  },
  "security": [
    {
      "OAuth2": [

      ]
    },
    {
      "Authenticator": [

      ]
    }
  ],
  "tags": [
    {
      "name": "Data centers"
    },
    {
      "name": "Organizations"
    },
    {
      "name": "Organization users"
    },
    {
      "name": "Managed organizations"
    },
    {
      "name": "Disks"
    },
    {
      "name": "Disk IO profiles"
    },
    {
      "name": "Disk templates"
    },
    {
      "name": "Disk template versions"
    },
    {
      "name": "GPU types"
    },
    {
      "name": "Virtual machines"
    },
    {
      "name": "Build",
      "description": "Endpoints used for building or creating new virtual machines"
    },
    {
      "name": "Power functions",
      "description": "Endpoints for performing power functions (i.e. start, stop etc...) on a virtual machine"
    },
    {
      "name": "Console",
      "description": "Endpoints for managing console access to a virtual machine"
    },
    {
      "name": "Virtual machine packages"
    },
    {
      "name": "SSH keys"
    },
    {
      "name": "API tokens"
    },
    {
      "name": "Disk backup policies",
      "description": "Endpoints for managing DNS zones/domains"
    },
    {
      "name": "DNS zones",
      "description": "Endpoints for managing DNS zones"
    },
    {
      "name": "Records",
      "description": "Endpoints for managing DNS records"
    },
    {
      "name": "Security groups",
      "description": "Endpoints for managing security groups"
    },
    {
      "name": "Security group rules",
      "description": "Endpoints for managing security group rules"
    },
    {
      "name": "File storage volumes"
    },
    {
      "name": "Networks"
    },
    {
      "name": "Network speed profiles"
    },
    {
      "name": "Virtual Networks"
    },
    {
      "name": "Address lists"
    },
    {
      "name": "Address list entries"
    },
    {
      "name": "Certificates"
    },
    {
      "name": "Load balancers"
    },
    {
      "name": "Load balancer rules"
    },
    {
      "name": "IP addresses"
    },
    {
      "name": "Virtual machine network interfaces"
    },
    {
      "name": "Tags"
    },
    {
      "name": "Virtual machine groups"
    },
    {
      "name": "Operating systems"
    },
    {
      "name": "Trash objects"
    },
    {
      "name": "Zones"
    },
    {
      "name": "Countries"
    },
    {
      "name": "Country states"
    },
    {
      "name": "Currencies"
    },
    {
      "name": "Tasks"
    },
    {
      "name": "Users"
    },
    {
      "name": "Object storage"
    },
    {
      "name": "Buckets"
    },
    {
      "name": "Access keys"
    }
  ],
  "x-tagGroups": [
    {
      "name": "API tokens",
      "tags": [
        "API tokens"
      ]
    },
    {
      "name": "Address lists",
      "tags": [
        "Address list entries",
        "Address lists"
      ]
    },
    {
      "name": "Certificates",
      "tags": [
        "Certificates"
      ]
    },
    {
      "name": "Countries",
      "tags": [
        "Countries"
      ]
    },
    {
      "name": "Country states",
      "tags": [
        "Country states"
      ]
    },
    {
      "name": "Currencies",
      "tags": [
        "Currencies"
      ]
    },
    {
      "name": "DNS zones",
      "tags": [
        "DNS zones",
        "Records"
      ]
    },
    {
      "name": "Data centers",
      "tags": [
        "Data centers"
      ]
    },
    {
      "name": "Disk IO profiles",
      "tags": [
        "Disk IO profiles"
      ]
    },
    {
      "name": "Disk backup policies",
      "tags": [
        "Disk backup policies"
      ]
    },
    {
      "name": "Disk template versions",
      "tags": [
        "Disk template versions"
      ]
    },
    {
      "name": "Disk templates",
      "tags": [
        "Disk templates"
      ]
    },
    {
      "name": "Disks",
      "tags": [
        "Disks"
      ]
    },
    {
      "name": "File storage volumes",
      "tags": [
        "File storage volumes"
      ]
    },
    {
      "name": "GPU types",
      "tags": [
        "GPU types"
      ]
    },
    {
      "name": "IP addresses",
      "tags": [
        "IP addresses"
      ]
    },
    {
      "name": "Load balancers",
      "tags": [
        "Load balancer rules",
        "Load balancers"
      ]
    },
    {
      "name": "Network speed profiles",
      "tags": [
        "Network speed profiles"
      ]
    },
    {
      "name": "Networks",
      "tags": [
        "Networks"
      ]
    },
    {
      "name": "Object storage",
      "tags": [
        "Access keys",
        "Buckets",
        "Object storage"
      ]
    },
    {
      "name": "Operating systems",
      "tags": [
        "Operating systems"
      ]
    },
    {
      "name": "Organizations",
      "tags": [
        "Managed organizations",
        "Organization users",
        "Organizations"
      ]
    },
    {
      "name": "SSH keys",
      "tags": [
        "SSH keys"
      ]
    },
    {
      "name": "Security groups",
      "tags": [
        "Security group rules",
        "Security groups"
      ]
    },
    {
      "name": "Tags",
      "tags": [
        "Tags"
      ]
    },
    {
      "name": "Tasks",
      "tags": [
        "Tasks"
      ]
    },
    {
      "name": "Trash objects",
      "tags": [
        "Trash objects"
      ]
    },
    {
      "name": "Users",
      "tags": [
        "Users"
      ]
    },
    {
      "name": "Virtual Networks",
      "tags": [
        "Virtual Networks"
      ]
    },
    {
      "name": "Virtual machine groups",
      "tags": [
        "Virtual machine groups"
      ]
    },
    {
      "name": "Virtual machine network interfaces",
      "tags": [
        "Virtual machine network interfaces"
      ]
    },
    {
      "name": "Virtual machine packages",
      "tags": [
        "Virtual machine packages"
      ]
    },
    {
      "name": "Virtual machines",
      "tags": [
        "Build",
        "Console",
        "Power functions",
        "Virtual machines"
      ]
    },
    {
      "name": "Zones",
      "tags": [
        "Zones"
      ]
    }
  ]
}