---
name: Nightly Checks

on:
  schedule:
    - cron: "0 0 * * *" # Midnight every day

jobs:
  schemas:
    name: Schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: 1.20
      - name: Check if bundled schemas are up to date
        run: make check-schemas
